#!/bin/bash
# SPECOPS Ralph Harness - Environment Initialization Script
# Generated by /spec-init for project: kanban-dashboard
#
# Run this at session start to quickly restore working state.
# Usage: source .ralph/init.sh

set -euo pipefail

# --- Configuration ---
PROJECT_NAME="kanban-dashboard"
PROJECT_DIR="/Users/sam/src/Kanban"
RALPH_DIR="${PROJECT_DIR}/.ralph"
FEATURES_JSON="${RALPH_DIR}/features.json"
PROGRESS_MD="${RALPH_DIR}/progress.md"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# --- Functions ---
log_info() { echo -e "${BLUE}ℹ${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }

# --- Verification ---
echo ""
echo -e "${BOLD}${CYAN}══════════════════════════════════════════${NC}"
echo -e "${BOLD}${CYAN}  SPECOPS Ralph Harness: ${PROJECT_NAME}${NC}"
echo -e "${BOLD}${CYAN}══════════════════════════════════════════${NC}"
echo ""

# Check working directory
if [[ "$(pwd)" != "${PROJECT_DIR}" ]]; then
  log_warn "Not in project directory. Changing to ${PROJECT_DIR}"
  cd "${PROJECT_DIR}" || { log_error "Failed to change directory"; exit 1; }
fi
log_success "Working directory: $(pwd)"

# Check ralph directory exists
if [[ ! -d "${RALPH_DIR}" ]]; then
  log_error "Ralph directory not found: ${RALPH_DIR}"
  log_info "Run /spec-init to initialize the harness"
  exit 1
fi
log_success "Ralph directory exists"

# Check features.json
if [[ ! -f "${FEATURES_JSON}" ]]; then
  log_error "Features file not found: ${FEATURES_JSON}"
  exit 1
fi
log_success "Features file exists"

# --- Git Status ---
echo ""
echo -e "${BOLD}Git Status:${NC}"
if git rev-parse --is-inside-work-tree &>/dev/null; then
  BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
  COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "none")
  DIRTY=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')

  echo -e "  ${DIM}Branch:${NC} ${CYAN}${BRANCH}${NC}"
  echo -e "  ${DIM}Commit:${NC} ${COMMIT}"
  if [[ "${DIRTY}" -gt 0 ]]; then
    echo -e "  ${DIM}Status:${NC} ${YELLOW}${DIRTY} uncommitted changes${NC}"
  else
    echo -e "  ${DIM}Status:${NC} ${GREEN}clean${NC}"
  fi
else
  log_warn "Not a git repository"
fi

# --- Progress Summary ---
echo ""
echo -e "${BOLD}Progress Summary:${NC}"

if command -v jq &>/dev/null; then
  TOTAL=$(jq '.features | length' "${FEATURES_JSON}")
  COMPLETED=$(jq '[.features[] | select(.status == "completed")] | length' "${FEATURES_JSON}")
  IN_PROGRESS=$(jq '[.features[] | select(.status == "in_progress")] | length' "${FEATURES_JSON}")
  BLOCKED=$(jq '[.features[] | select(.status == "blocked")] | length' "${FEATURES_JSON}")
  PENDING=$(jq '[.features[] | select(.status == "pending")] | length' "${FEATURES_JSON}")

  PCT=$((COMPLETED * 100 / TOTAL))

  echo -e "  ${DIM}Total:${NC}       ${TOTAL} features"
  echo -e "  ${DIM}Completed:${NC}   ${GREEN}${COMPLETED}${NC} (${PCT}%)"
  echo -e "  ${DIM}In Progress:${NC} ${YELLOW}${IN_PROGRESS}${NC}"
  echo -e "  ${DIM}Blocked:${NC}     ${RED}${BLOCKED}${NC}"
  echo -e "  ${DIM}Pending:${NC}     ${PENDING}"

  # Progress bar
  FILLED=$((PCT / 5))
  EMPTY=$((20 - FILLED))
  BAR=$(printf '█%.0s' $(seq 1 $FILLED 2>/dev/null) || true)
  BAR+=$(printf '░%.0s' $(seq 1 $EMPTY 2>/dev/null) || true)
  echo -e "  ${DIM}Progress:${NC}    [${GREEN}${BAR}${NC}] ${PCT}%"
else
  log_warn "jq not installed - cannot parse features.json"
  echo -e "  ${DIM}See:${NC} ${FEATURES_JSON}"
fi

# --- Current Feature ---
echo ""
CURRENT_FEATURE_FILE="${RALPH_DIR}/current-feature.txt"
if [[ -f "${CURRENT_FEATURE_FILE}" ]] && [[ -s "${CURRENT_FEATURE_FILE}" ]]; then
  CURRENT=$(cat "${CURRENT_FEATURE_FILE}")
  echo -e "${BOLD}Current Feature:${NC} ${CYAN}${CURRENT}${NC}"

  if command -v jq &>/dev/null; then
    FEATURE_NAME=$(jq -r --arg id "$CURRENT" '.features[] | select(.id == $id) | .name' "${FEATURES_JSON}")
    FEATURE_DESC=$(jq -r --arg id "$CURRENT" '.features[] | select(.id == $id) | .description' "${FEATURES_JSON}" | head -c 100)
    echo -e "  ${DIM}Name:${NC} ${FEATURE_NAME}"
    echo -e "  ${DIM}Desc:${NC} ${FEATURE_DESC}..."
  fi
else
  echo -e "${BOLD}Current Feature:${NC} ${DIM}none${NC}"
fi

# --- Next Available ---
echo ""
echo -e "${BOLD}Ready to Start:${NC}"
if command -v jq &>/dev/null; then
  READY=$(jq -r '
    .features
    | map(select(.status == "pending"))
    | sort_by(.priority)
    | .[0:3]
    | .[]
    | "  \(.id): \(.name)"
  ' "${FEATURES_JSON}" 2>/dev/null || echo "  (unable to compute)")

  if [[ -z "${READY}" ]]; then
    echo -e "  ${DIM}No features ready (check blocked features)${NC}"
  else
    echo -e "${CYAN}${READY}${NC}"
  fi
fi

# --- Quick Commands ---
echo ""
echo -e "${BOLD}Quick Commands:${NC}"
echo -e "  ${DIM}Resume work:${NC}     /spec-build ${PROJECT_NAME} --resume"
echo -e "  ${DIM}Check status:${NC}    /spec-status ${PROJECT_NAME}"
echo -e "  ${DIM}Verify features:${NC} /spec-verify ${PROJECT_NAME}"
echo -e "  ${DIM}Hydrate tasks:${NC}   /spec-hydrate ${PROJECT_NAME}"

echo ""
echo -e "${GREEN}${BOLD}Ready to work!${NC}"
echo ""
